spring:
  application:
    name: ticket-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/The-Petros-Team/travel-agency-config-repo
          search-paths:
            - configurations